### ISSUE TITLE
[bug] Excessive swap may result in slower builds

### ISSUE THREAD

**Issue by WGB5445** [starcoinorg/starcoin-cookbook#70]
# Document Bug Report

**Document URL:**

https://starcoinorg.github.io/starcoin-cookbook/zh/docs/getting-started/install/build/
**Describe the document's bug:**

In my experience, using a larger Swap than memory will result in slower loading of links
At the same time, too many cpu threads are also one of the reasons for link errors.
It is more appropriate to use a single thread for 4GB Ram, otherwise there may be a compilation error and need to be recompiled several times

**Other information:**

**Comment by geometryolife** [comment]
I do some tests, and got the following conclusions:

In the case of low machine configuration, if the `swap` is enabled, then the size of swap must be greater than or equal to RAM, otherwise the link will fail.
Another situation is that if the memory is large enough, the best way is to disable `swap` to reduce the time of disk IO.

**Notice:**
For low configuration machines, the core number of control is the key to greatly improve the compilation efficiency.

For example:

```shell
cargo build -j 1
```

**Comment by WGB5445** [comment]
I think your testing process is great
you can add relevant conclusions to the document
These conclusions can allow users to find the direction of the solution
